name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: yarn install

      - name: build production project
        if: always()
        run: yarn run build

      - name: linting typescript
        if: always()
        run: yarn run lint:ts

      - name: linting css
        if: always()
        run: yarn run lint:scss

      - name: unit testing
        if: always()
        run: yarn run test:unit

      - name: build storybook
        if: always()
        run: yarn run storybook:build




